### ISSUE TITLE
Inconsistent use of static vs non-static assertions

### ISSUE THREAD

**Issue by denniskoster** [daniel-de-wit/lighthouse-sanctum#61]
The use of static vs non-static assertions in the test cases is inconsistent. For instance: https://github.com/daniel-de-wit/lighthouse-sanctum/blob/master/tests/Integration/GraphQL/Mutations/RegisterTest.php#L45

For code consistency it would be better to pick either `$this->assert` or `static::assert`.

**Comment by wimski** [comment]
This is not inconsistent. Most assertion methods are `static` and therefore called as such (`assertSame` for example). The `assertDatabaseHas` method however is not `static` and therefore not called as such.

```php
trait InteractsWithDatabase
{
    protected function assertDatabaseHas($table, array $data, $connection = null)
}
```
