### ISSUE TITLE
Typo on instructions

### ISSUE THREAD

**Issue by loureirorg** [daniel-de-wit/lighthouse-sanctum#68]
There's a typo on README.MD, step 3:

It says:
```graphql
#import sanctum.grapqhl
```

But should be:
```graphql
#import sanctum.graphql
```

The typo is on `grapqhl`.

It took me an hour to find out what I was doing wrong. Lol.

**Comment by daniel-de-wit** [comment]
The readme has been updated. Thanks for reporting!
