### ISSUE TITLE
@auth directive does not point to sanctum user

### ISSUE THREAD

**Issue by LiamKarlMitchell** [daniel-de-wit/lighthouse-sanctum#74]
In config/lighthouse.php I had to set this for @auth to work.

```
'guard' => 'sanctum',
```

Didn't see it in the readme.

```
    "Get the logged in user."
    me: User @auth
```

or
```
me: @auth('sanctum')
```

sanctum.graphql
```graphql
extend type Query {
    me: User @auth
}
```

**Comment by wimski** [comment]
When using Sanctum it's pretty much implied that you set it as the guard. The documentation of this package only deals with the specifics of using it with Lighthouse.
