### ISSUE TITLE
session does not seem to work for logged in graphql user

### ISSUE THREAD

**Issue by LiamKarlMitchell** [daniel-de-wit/lighthouse-sanctum#75]
Wanting to store stuff in session and get it out again in custom mutators/resolvers..

But it seems like every time I read the session data it is not set.
How can I enable laravel sessions for the token?

**Comment by daniel-de-wit** [comment]
This package only supports using the [API Token Authentication](https://laravel.com/docs/9.x/sanctum#api-token-authentication) of Laravel Sanctum.
