### ISSUE TITLE
Option to change email to username

### ISSUE THREAD

**Issue by xorinzor** [daniel-de-wit/lighthouse-sanctum#76]
In my application I use a username/password combination rather then email/password.

I updated the sanctum.graphql `login` mutation to accept a `username` parameter instead of `email`, but it turns out the PHP controller always assumes an `email`.

It'd be great if this would either be configurable, or would accept both and select which one to use based on which is provided.

**Comment by xorinzor** [comment]
awesome, thanks for the quick fix!

**Comment by daniel-de-wit** [comment]
No problem @xorinzor :)

I just released a new version https://github.com/daniel-de-wit/lighthouse-sanctum/tree/2.1.0
