### ISSUE TITLE
Nuwave/Lighthouse v6

### ISSUE THREAD

**Issue by eshimischi** [daniel-de-wit/lighthouse-sanctum#91]
v6 was released [v6.0.0-alpha.1](https://github.com/nuwave/lighthouse/releases/tag/v6.0.0-alpha.1)

**Comment by eshimischi** [comment]
Of course it will be better to adapt this version after beta/rc

**Comment by eshimischi** [comment]
beta was released [v6.0.0-beta.1](https://github.com/nuwave/lighthouse/releases/tag/v6.0.0-beta.1)

**Comment by eshimischi** [comment]
v5 was just released [v6.0.0](https://github.com/nuwave/lighthouse/releases/tag/v6.0.0) @daniel-de-wit

**Comment by gabtorr** [comment]
Hi! So when is going to be available the support for v6?

**Comment by daniel-de-wit** [comment]
Please check out https://github.com/daniel-de-wit/lighthouse-sanctum/releases/tag/3.0.0 and let me know how it goes.
